name: Node.js CI Pipelin

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Create test results folder
        run: |
         mkdir -p test
         echo "Test 1: pass" > test/result.txt
         echo "<h1>All Tests Passed</h1>" > test/reports.html

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results             # name of the artifact
          path: test/
          overwrite: true 

  deploy:
   runs-on: ubuntu-latest
   needs: test
   steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download test results node 20
        uses: actions/download-artifact@v4
        with:
          name: test-results        # same name as uploaded
          path: test/

      - name: Verify downloaded files
        run: |
          echo "Node 20 results:"
          ls -la test/

      - name: Deploy
        run: |
          echo "Deploying application..."
          echo "All tests passed on node 20 and 22!"
          echo "Deploy successful! ✅"

      
